<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Queue Simulation</title>
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="style.css" rel="stylesheet">
</head>
<body class="bg-light">

<div class="container py-5">
    <div class="text-center mb-5">
        <h1 class="display-5 fw-bold text-dark">Simulation Dashboard</h1>
        <p class="lead text-muted">Web-based Multi-stage Queue System</p>
        <button id="btnAddUser" class="btn btn-primary btn-lg mt-3 shadow-sm px-5">➕ Tambah Antrian</button>
        <button id="btnEndSim" class="btn btn-danger btn-lg mt-3 ms-2 shadow-sm px-4">🛑 Akhiri Simulasi</button>
        <a href="history.php" class="btn btn-outline-secondary btn-lg mt-3 ms-2 shadow-sm">📊 Lihat Riwayat Terpisah</a>
    </div>

    <div class="row gx-4">
        <!-- Simulation Area -->
        <div class="col-lg-8">
            <div id="stages-container">
                <!-- Stages will be generated by JS -->
            </div>
        </div>

        <!-- Log Panel -->
        <div class="col-lg-4">
            <div class="card shadow-sm border-0 bg-dark text-white h-100 rounded-4" style="min-height: 600px;">
                <div class="card-header border-secondary bg-dark pt-4 pb-3">
                    <h5 class="mb-0 fw-bold d-flex align-items-center">
                        <span class="me-2">📝</span> Activity Log
                    </h5>
                </div>
                <div class="card-body log-panel" id="logPanel">
                    <div class="text-secondary small">Simulation started... Waiting for actions.</div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="script.js"></script>

</body>
</html>
